version: 2

formats:
  - htmlzip

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  builder: html
  configuration: docs/conf.py
#  fail_on_warning: true
