#!/usr/bin/env python
#
# phasespace documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
#

import os
import warnings

# Suppress TensorFlow and zfit warnings during documentation build
os.environ["ZFIT_DISABLE_TF_WARNINGS"] = "1"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"

# Suppress all Python warnings during documentation build
warnings.filterwarnings("ignore")

# Suppress TensorFlow C++ logging to stderr
import logging  # noqa: E402

logging.getLogger("tensorflow").setLevel(logging.ERROR)

# Try to suppress absl logging
try:
    from absl import logging as absl_logging

    absl_logging.set_verbosity(absl_logging.ERROR)
    absl_logging.set_stderrthreshold(absl_logging.ERROR)
except ImportError:
    pass

import phasespace  # noqa: E402

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# use for classes the class and the __init__ docs combined
autoclass_content = "both"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
    "sphinx_math_dollar",
    "jupyter_sphinx",
    "myst_nb",
]


mathjax3_config = {
    "tex2jax": {
        "inlineMath": [["\\(", "\\)"]],
        "displayMath": [["\\[", "\\]"]],
    },
}
using_numpy_style = False  # False -> google style

# Napoleon settings (convert numpy/google docstrings to proper ReST
napoleon_google_docstring = not using_numpy_style
napoleon_numpy_docstring = using_numpy_style
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "TensorFlow PhaseSpace"
copyright = "2024, Albert Puig Navarro"
author = "Albert Puig Navarro"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = phasespace.__version__
# The full version, including alpha/beta/rc tags.
release = phasespace.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# Suppress specific warnings
suppress_warnings = [
    "misc.highlighting_failure",  # Suppress syntax highlighting warnings
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# # makes the jupyter extension executable
# jupyter_sphinx_thebelab_config = {
#     "requestKernel": True,
#     "binderOptions": {
#         "repo": "zfit/phasespace",
#         "binderUrl": "https://mybinder.org",
#         "repoProvider": "github",
#     },
# }

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"
html_theme_options = {
    "logo": {
        "text": "phasespace",
    },
    # Navbar configuration
    "navbar_start": ["navbar-logo"],
    "navbar_center": ["navbar-nav"],
    "navbar_end": ["theme-switcher", "navbar-icon-links"],
    "navbar_persistent": ["search-button-field"],
    "navbar_align": "content",
    # Sidebar configuration
    "primary_sidebar_end": [],
    "secondary_sidebar_items": ["page-toc", "edit-this-page"],
    "show_toc_level": 2,
    # Footer configuration
    "footer_start": ["copyright"],
    "footer_center": ["sphinx-version"],
    # Navigation options
    "navigation_with_keys": True,
    "show_prev_next": True,
    "show_nav_level": 3,
    "navigation_depth": 3,
    # External links
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/zfit/phasespace",
            "icon": "fa-brands fa-github",
            "type": "fontawesome",
        },
    ],
}

# Sidebar configuration using glob patterns
html_sidebars = {
    "**": ["sidebar-nav-bs"],
}

# Configure navigation links in the navbar
html_context = {
    "default_mode": "light",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "phasespacedoc"

# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "phasespace.tex",
        "TensorFlow PhaseSpace Documentation",
        "Albert Puig Navarro",
        "manual",
    ),
]

# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, "phasespace", "TensorFlow PhaseSpace Documentation", [author], 1)
]

# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "phasespace",
        "TensorFlow PhaseSpace Documentation",
        author,
        "phasespace",
        "One line description of project.",
        "Miscellaneous",
    ),
]
